version: '3.7'
services:
  student-database:
    image: postgres:latest

    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: student-db
    container_name: student-database

    ports:
      - "5432:5432"